blog/models.py
'''
    留言板-数据存储
'''
from datetime import datetime
from app import db

class TbMessage(db.Model):
    id = db.Column(db.String(40), primary_key=True)
    title = db.Column(db.String(20))
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow,index=True)

    def __repr__(self):
        return "<Message body %r>" %self.body

def init_db():
    db.create_all()

blog/forms/board.py
'''
    留言板 - Form
'''
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField,SubmitField
from wtforms.validators import DataRequired, Length

class MessageForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired('请输入标题!'), Length(5,20,'长度要介于(5-20)！')])
    body = TextAreaField('消息', validators=[DataRequired('请输入消息!'),Length(10,200,'长度要介于(10-200)')])
    submit = SubmitField('发布')

blog/__init__.py
from blog.views.auth import bp_auth
from blog.views.admin import bp_admin
from blog.views.blog import bp_blog
from blog.views.board import bp_board
#蓝本注册
def register_blueprints(app):
    #注册蓝本
    app.register_blueprint(bp_auth,  url_prefix='/auth')
    app.register_blueprint(bp_admin, url_prefix='/admin')
    app.register_blueprint(bp_blog,  url_prefix='/blog')
    app.register_blueprint(bp_board, url_prefix='/board')

blog/views/admin.py
from flask import Blueprint,render_template,url_for,redirect
bp_admin = Blueprint('admin', __name__)

@bp_admin.route('/')
def index():
    return render_template('index.html')

blog/views/auth.py
from flask import Blueprint,render_template,session
bp_auth = Blueprint('auth', __name__)

#登录
@bp_auth.route('/login')
def login():
    return render_template('auth/login.html')
#登出
@bp_auth.route('/logout')
def logout():
    return render_template('auth/logout.html')

blog/views/blog.py
from flask import Blueprint
bp_blog = Blueprint('blog', __name__)

blog/views/board.py
'''
    留言板模块
'''
from flask import Blueprint,url_for,redirect,render_template,flash
from blog.forms.board import MessageForm
from blog.models import TbMessage
from app import db
import uuid
#实例化留言板蓝本
bp_board = Blueprint('board', __name__)
#留言板页面
@bp_board.route('/', methods=['GET','POST'])
def index():
    messages = TbMessage.query.order_by(TbMessage.timestamp.desc()).all()
    form = MessageForm()
    if form.validate_on_submit():
        message = TbMessage(id=uuid.uuid4().hex, title=form.title.data, body=form.body.data)
        db.session.add(message)
        db.session.commit()
        flash('消息已发布!!!')
        return redirect(url_for('.index'))   #重定向index视图,获取最新数据,使用蓝本，url_for需要将endpoint添加完整"board.index"，本蓝本内加点即可".index"
    return render_template('board/index.html', form=form, messages=messages)
    #return render_template('board/index.html', form=form)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
{# 显式地使用with context声明传人当前模板的上下文 #}
{% from 'macros/macros.html' import static_file with context %}
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% block title %}Base Title{% endblock %}</title>
    <!-- 使用宏导入静态文件 -->
    {{static_file('icon', 'images/icon/favicon.ico')}}
    {{static_file('css','css/bootstrap.min.css')}}
    {{static_file('css','css/jquery-confirm.min.css')}}
    {{static_file('css','css/all.min.css')}}
    {# --------- 引入子页面自己的css文件 --------- #}
    {% block links %}{% endblock %}
    {{static_file('js','js/jquery-3.6.0.min.js')}}
    {{static_file('js','js/popper.min.js')}}
    {{static_file('js','js/bootstrap.min.js')}}
    {{static_file('js','js/jquery-confirm.min.js')}}
    <!-- 生成执行时间渲染函数 -->
    {{ moment.include_moment(local_js=url_for('static',filename='js/moment/moment-with-locales.js')) }}
    <!-- 设置自动识别显示语言 -->
    {{ moment.locale(auto_detect=True) }}
    {# --------- 引入子页面自己的JavaScript文件 --------- #}
    {% block scripts %}{% endblock %}
    {# --------- 编写子页面自己的css样式 --------- #}
    {% block styles %}{% endblock %}
    {% endblock %}
</head>
<body>
    <header style="margin-top:20px;">
        {% block header %}
            <div class="container">
                <div class="row">
                    <div class="col text-center">
                        <h1><a href = "{{url_for('admin.index')}}">博客</a></h1>
                    </div>
                </div>
            </div>
        {% endblock %}
    </header>
    <main>
        {% block main %}{% endblock %}
    </main>
    <footer>
        {% block footer %}{% endblock %}
    </footer>
    <script>
        $(function(){
            //alert('base is ready')
        })
        {# --------- 引入子页面JavaScritp变量 --------- #}
        {% block variable %}{% endblock %}
        {% block ready %}{% endblock %}
        {# --------- 引入子页面自己的JavaScript函数 --------- #}
        {% block function %}
        function allAlert(){
           $.alert({
               type:'red',
               //icon:'fa fa-info',
               title:'提示',
               content: 'I Am Ready To Go！',
               onClose:function(){

               }
           })
        }
        function allClick(){
            alert('All Click!!!')
        }
        {% endblock %}
    </script>
</body>
</html>

blog/templates/board/index.html
{% extends 'base.html' %}
{% block title %}留言板{% endblock %}
<header>
    {% block header %}
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <h1><a href = "{{url_for('board.index')}}">博客-留言板</a></h1>
                    <small>Administrator : {{ admin_name }}</small>
                </div>
            </div>
        </div>
    {% endblock %}
</header>
{% block main %}
<div class="container">
    {% if get_flashed_messages() %}
    <div class="row">
        <div class="col">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              <small>留言已发布!!!</small>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col">
          <form method="post">
              <!-- 表单必须填写csrf验证，否则验证会一直无法通过！！！ -->
              {{ form.csrf_token }}
              <div class="mb-3">
                  {{ form.title.label(class='form-label')}}
                  {{ form.title(class='form-control',placeholder='请输入标题!')}}
                  {% if form.title.errors %}
                    {% for error in form.title.errors %}
                        <small class="text-warning">{{ error }}</small>
                    {% endfor %}
                  {% endif %}
              </div>
              <div class="mb-3">
                  {{ form.body.label(class='form-label')}}
                  {{ form.body(class='form-control',placeholder='请输入消息',row='3')}}
                  {% if form.body.errors %}
                    {% for error in form.body.errors %}
                        <small class="text-warning">{{ error }}</small>
                    {% endfor %}
                  {% endif %}
              </div>
              <div class="mb-3">
                  <button class="btn btn-outline-primary" type="submit"><i class="fas fa-cloud-upload-alt"></i>&nbsp;&nbsp;发布</button>&nbsp;&nbsp;&nbsp;&nbsp;
                  <!--button class="btn btn-outline-success" onclick="checkdate('2021-03-02')">校验日期</button-->
              </div>
          </form>
        </div>
    </div>
    <div class="row">
        <div class="col-6"><h4>{{ messages|length }}条消息:</h4></div>
        <div class="col-6 text-end">
            <a href="#bottom" id = "top"><h4><i class="fas fa-arrow-circle-down"></i></h4></a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="list-group">
                {% for message in messages %}
                <a href="#" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                      <h6 class="mb-1">{{ message.title }}</h6>
                      <small>{{ moment(message.timestamp).fromNow(refresh=True) }}</small>
                    </div>
                    <p class="mb-1"><h5>{{ message.body }}</h5></p>
                    <!--small>{{ message.timestamp.strftime('%Y/%m/%d %H:%M') }}</--small-->
                    <!-- 使用MomentJS渲染日期 -->
                    <small>{{ moment(message.timestamp).format('LLL')}}</small>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
     <div class="row">
        <div class="col text-center"><a href="#top" id = "bottom"><h4><i class="fas fa-arrow-circle-up"></i></h4></a></div>
    </div>
</div>
{% endblock %}
<script>
    {% block function%}
    {{ super() }}
    function checkdate(value){
        var myDate = new Date();
        var now = myDate.valueOf();
        alert('Now : '+ now)
        var time = new Date(value).valueOf();
        alert('Check time : ' + time)
        if(now>time){
            alert('日期小于当天，可以使用！')
          return true;
        }else{
            alert('日期大于当天，不可用')
          return false;
        }
    }
    {% endblock %}
</script>

blog/templates/index.html
{% extends 'base.html' %}
{% block title %}博客主页{% endblock %}
{% block main %}
<div class="container">
    <div class="row">
        <div class="col text-center">
          <h1>Blog Home Page</h1>
          <h2>Administrator is : {{ admin_name }}</h2>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/macros/macros.html
<!-- 宏加载静态资源文件 -->
{% macro static_file(type, file_or_url, local=True) %}
    {% if local %}
        {% set file_or_url = url_for('static', filename = file_or_url) %}
    {% endif %}
    {% if type == 'css' %}
        <link rel = "stylesheet" type = "text/css" href = "{{file_or_url}}">
    {% endif %}
    {% if type == 'icon' %}
        <link rel = "icon" type = "image/x-icon" href = "{{file_or_url}}">
    {% endif %}
    {% if type == 'js' %}
        <script type = "text/javascript" src = "{{file_or_url}}"></script>
    {% endif %}
{% endmacro %}